/*
  Copyright (c), 2001-2022, Oritek Tech. Co., Ltd.
 */

#ifndef SYS_CTRL_H
#define SYS_CTRL_H

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

typedef enum {
    VI_ONLINE_VIDEO_NORM_VPROC_ONLINE = 0, /* OT_VI_AIISP_MODE_DEFAULT OT_VI_ONLINE_VPROC_ONLINE */
    VI_ONLINE_VIDEO_NORM_VPROC_OFFLINE = 1, /* OT_VI_AIISP_MODE_DEFAULT OT_VI_ONLINE_VPROC_OFFLINE */
    VI_ONLINE_VIDEO_ADVANCED_VPROC_OFFLINE = 2, /* OT_VI_AIISP_MODE_AIDRC OT_VI_ONLINE_VPROC_OFFLINE */
    VI_OFFLINE_VIDEO_NORM_VPROC_ONLINE = 3, /* OT_VI_AIISP_MODE_DEFAULT OT_VI_OFFLINE_VPROC_ONLINE */
    VI_OFFLINE_VIDEO_ADVANCED_VPROC_OFFLINE = 4, /* OT_VI_AIISP_MODE_AIDRC OT_VI_OFFLINE_VPROC_OFFLINE */

    VI_ONLINE_VIDEO_ADVANCED_VPROC_ONLINE = 5, /* OT_VI_AIISP_MODE_AIDRC OT_VI_ONLINE_VPROC_ONLINE */
    VI_OFFLINE_VIDEO_NORM_VPROC_OFFLINE = 6, /* OT_VI_AIISP_MODE_DEFAULT OT_VI_OFFLINE_VPROC_OFFLINE */
    VI_OFFLINE_VIDEO_ADVANCED_VPROC_ONLINE = 7, /* OT_VI_AIISP_MODE_AIDRC OT_VI_OFFLINE_VPROC_ONLINE */

    VI_VPROC_ONLINE_BUTT
} vi_vproc_online_mode;

void sys_ctl(int online_flag);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif

#endif /* SYS_CTRL_H */
