#ifndef __OT_MEDIA_PIPE_COMMON_H__
#define __OT_MEDIA_PIPE_COMMON_H__

#include "ot_eis_type.h"
#include "ot_eis_errno.h"
#include "ot_eis_mod.h"
#include "ot_eis_media_common.h"

#ifdef __cplusplus
extern "C" {
#endif

#define OT_MAX_BIND_PORT_NUM  6

typedef enum {
    OT_MEDIA_PIPE_NO_EXIST = 0x20,
    OT_MEDIA_PIPE_NODE_UNBIND,
    OT_MEDIA_PIPE_NOT_INIT,
    OT_MEDIA_PIPE_DEPEND_NOT_READY,
    OT_MEDIA_PIPE_LINK_EXIST,
    OT_MEDIA_PIPE_BUTT
} ot_media_pipe_err_code;

#define OT_ERR_MEDIA_PIPLINE_DEFINE(errno) OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_PIPLINE, errno)

#define OT_ERR_MEDIA_PIPLINE_NULL_PTR        OT_ERR_MEDIA_PIPLINE_DEFINE(OT_EIS_ERRNO_NULL_PTR)
#define OT_ERR_MEDIA_PIPLINE_ILLEGAL_PAARAM  OT_ERR_MEDIA_PIPLINE_DEFINE(OT_EIS_ERRNO_ILLEGAL_PARAM)
#define OT_ERR_MEDIA_PIPLINE_NO_MEM          OT_ERR_MEDIA_PIPLINE_DEFINE(OT_EIS_ERRNO_NO_MEM)
#define OT_ERR_MEDIA_PIPE_NODE_UNBIND        OT_ERR_MEDIA_PIPLINE_DEFINE(OT_MEDIA_PIPE_NODE_UNBIND)
#define OT_ERR_MEDIA_PIPE_NOT_EXIST          OT_ERR_MEDIA_PIPLINE_DEFINE(OT_MEDIA_PIPE_NO_EXIST)
#define OT_ERR_MEDIA_PIPE_NOT_INIT           OT_ERR_MEDIA_PIPLINE_DEFINE(OT_MEDIA_PIPE_NOT_INIT)
#define OT_ERR_MEDIA_PIPE_DEPEND_NOT_READY   OT_ERR_MEDIA_PIPLINE_DEFINE(OT_MEDIA_PIPE_DEPEND_NOT_READY)
#define OT_ERR_MEDIA_PIPE_NOT_SUPPORT        OT_ERR_MEDIA_PIPLINE_DEFINE(OT_EIS_ERRNO_NO_SUPPORT)
#define OT_ERR_MEDIA_PIPE_LINK_EXIST         OT_ERR_MEDIA_PIPLINE_DEFINE(OT_MEDIA_PIPE_LINK_EXIST)

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
