;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                           mediepipe parameter                                        ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[mediapipe_comm]
;; the number of mediapipe
mediapipe_num                      = "1"
;; 0: vi offline vproc offline; 1: vi offline vproc online;
;; 2: vi online vproc offline;  3: vi online vproc online
vi_vproc_mode_type                 = "0"
;; refer to sample_vo_display_mode on sdk
vo_display_dev                     = "ONE_IN_PORT_MIPI_AV069HDT_1280X720"
vo_fps                             = "50"
;; the count of vrb buf_blks
vrb_buf_blks                       = "9, 9, 9"



;;;;;;;;;;;;;;mediapipe_parameter;;;;;;;;;;;;;;
;;;;;; enable for threads ;;;;;;
[thread_enable_0]
thr_enable_normal                  = "1"
thr_enable_clut                    = "0"
thr_enable_mce                     = "0"
thr_enable_deflicker               = "0"
thr_enable_dehaze                  = "1"
thr_enable_abnr                    = "0"
thr_enable_iqt                     = "0"
thr_enable_vp2vo                   = "0"

;;;;;; delay for threads ;;;;;;
[thread_usleep_0]
thr_usleep_normal                  = "100000"
thr_usleep_clut                    = "100000"
thr_usleep_dehaze                  = "200000"
thr_usleep_abnr                    = "100000"
thr_usleep_fp_pipe                 = "5000"
thr_usleep_fp_chn                  = "10000"

[mediapipe_0]
;;;;;;common;;;;;
;; 0: without sensor; 1: with sensor
vi_with_sensor                     = "1"
;; refer to sample_sns_type on sdk
vi_sns_type                        = "SONY_IMX623_MIPI_3M_60FPS_16BIT"
;; 0: do not create vi pipe frame pool; 1: create vi pipe frame pool
vproc_pipe_frame_pool_enable       = "1"
;; 0: do not create vproc chn frame pool; 1: create vproc chn frame pool; chn0 must be disable
vproc_chn_frame_pool_enable        = "0, 1, 0, 1"
;; 0: disable; 1: enable
vproc_chn_enable                   = "1, 1, 0, 1"
vproc_chn_crop_enable              = "0, 0, 0, 0"
vproc_chn_mirror_enable            = "0, 0, 0, 0"
vproc_chn_rotation_enable          = "0, 0, 0, 0"
;; 0: do not save video; 1: save video
save_video_enable                  = "0"

;;;;;;;vi;;;;;;;
;; the dev id of sensor
vi_dev_id                          = "0"
;;;;;;vproc;;;;;
;; the src_frame_rate of vproc chn
vproc_chn_frc_src                  = "50, 50, 50, 50"
;; the dst_frame_rate of vproc chn
vproc_chn_frc_dst                  = "50, 50, 50, 25"
;; the size of vproc chn
vproc_chn_img_w                    = "1936, 1936, 1936, 448"
vproc_chn_img_h                    = "1552,  1552, 1552, 384"
;; 0: ABS; 1: RATIO
vproc_chn_crop_mode                = "0, 0, 0, 0"
vproc_chn_crop_x                   = "0, 0, 0, 0"
vproc_chn_crop_y                   = "0, 0, 0, 0"
vproc_chn_crop_w                   = "0, 500, 0, 0"
vproc_chn_crop_h                   = "0, 300, 0, 0"
;; 0: 0 degree; 1: 90 degrees; 2: 180 degrees; 3: 270 degrees
vproc_chn_rotation                 = "0, 0, 0, 0"

;;;;;;;venc;;;;;
;; the chn id of vproc to be saved
venc_chn_id                        = "1"
;; 0: HEVC; 1: H264; 2:JPEG;
venc_codec_format                  = "0"
venc_stream_buf_size               = "6220800"
venc_gop                           = "50"
venc_rc_mode                       = "0"
venc_statis_time                   = "1"
venc_max_bit_rate                  = "40960"
venc_short_statis_time             = "1"
venc_long_statis_time              = "1"
venc_long_max_bit_rate             = "30720"
venc_long_min_bit_rate             = "20480"
venc_gop_mode                      = "0"
venc_qp_delta_ip                   = "2"
venc_max_file_size_m               = "250"
;;;;;;;compress;;;;;
;; 0:NONE, 1:SEG, 2:LINE, 3:FRAME
comp_mode_vi_pipe                  = "0"
comp_mode_vi_chn                   = "0"
comp_mode_vproc_pipe               = "0, 0, 0, 0"
comp_mode_vproc_chn                = "0, 0, 0, 0"
comp_mode_3dnr                     = "0"
;;;;;;;;;;;;;;mce_parameter;;;;;;;;;;;;;;
[mce_0]
;; the id of vproc chn frame pool to send to mce
mce_chn_id                         = "3"
[debug_0]
debug_deflicker_enable             = "0"
[vp2vo_0]
vp2vo_chn_id                       = "0, -1, -1, -1"
vp2vo_on_one_thread                = "0"

;;;;;;;;;;;;;;mediapipe_parameter;;;;;;;;;;;;;;
;;;;;; enable for threads ;;;;;;
[thread_enable_1]
thr_enable_normal                  = "1"
thr_enable_clut                    = "1"
thr_enable_mce                     = "1"
thr_enable_deflicker               = "1"
thr_enable_dehaze                  = "1"
thr_enable_abnr                    = "0"
thr_enable_iqt                     = "0"
thr_enable_vp2vo                   = "0"

;;;;;; delay for threads ;;;;;;
[thread_usleep_1]
thr_usleep_normal                  = "200000"
thr_usleep_clut                    = "40000"
thr_usleep_dehaze                  = "200000"
thr_usleep_abnr                    = "200000"
thr_usleep_fp_pipe                 = "10000"
thr_usleep_fp_chn                  = "10000"

[mediapipe_1]
;;;;;;common;;;;;
;; 0: without sensor; 1: with sensor
vi_with_sensor                     = "1"
;; refer to sample_sns_type on sdk
vi_sns_type                        = "SONY_IMX623_MIPI_3M_60FPS_16BIT"
;; 0: do not create vi pipe frame pool; 1: create vi pipe frame pool
vproc_pipe_frame_pool_enable       = "1"
;; 0: do not create vproc chn frame pool; 1: create vproc chn frame pool
vproc_chn_frame_pool_enable        = "0, 0, 0, 1"
;; 0: disable; 1: enable
vproc_chn_enable                   = "1, 0, 0, 1"
vproc_chn_crop_enable              = "0, 0, 0, 0"
vproc_chn_mirror_enable            = "0, 0, 0, 0"
vproc_chn_rotation_enable          = "0, 0, 0, 0"
;; 0: do not save video; 1: save video
save_video_enable                  = "0"

;;;;;;;vi;;;;;;;
;; the dev id of sensor
vi_dev_id                          = "2"
;;;;;;vproc;;;;;
;; the src_frame_rate of vproc chn
vproc_chn_frc_src                  = "50, 50, 50, 50"
;; the dst_frame_rate of vproc chn
vproc_chn_frc_dst                  = "50, 50, 50, 25"
;; the size of vproc chn
vproc_chn_img_w                    = "1280, 1280, 1280, 448"
vproc_chn_img_h                    = "768,  768, 768, 384"
;; 0: ABS; 1: RATIO
vproc_chn_crop_mode                = "0, 0, 0, 0"
vproc_chn_crop_x                   = "0, 0, 0, 0"
vproc_chn_crop_y                   = "0, 0, 0, 0"
vproc_chn_crop_w                   = "0, 0, 0, 0"
vproc_chn_crop_h                   = "0, 0, 0, 0"
;; 0: 0 degree; 1: 90 degrees; 2: 180 degrees; 3: 270 degrees
vproc_chn_rotation                 = "0, 0, 0, 0"
;;;;;;;venc;;;;;
;; the chn id of vproc to be saved
venc_chn_id                        = "1"
;; 0: HEVC; 1: H264; 2:JPEG;
venc_codec_format                  = "0"
venc_stream_buf_size               = "6220800"
venc_gop                           = "50"
venc_rc_mode                       = "0"
venc_statis_time                   = "1"
venc_max_bit_rate                  = "40960"
venc_short_statis_time             = "1"
venc_long_statis_time              = "1"
venc_long_max_bit_rate             = "30720"
venc_long_min_bit_rate             = "20480"
venc_gop_mode                      = "0"
venc_qp_delta_ip                   = "2"
venc_max_file_size_m               = "250"
;;;;;;;compress;;;;;
;; 0:NONE, 1:SEG, 2:LINE, 3:FRAME
comp_mode_vi_pipe                  = "0"
comp_mode_vi_chn                   = "0"
comp_mode_vproc_pipe               = "0, 0, 0, 0"
comp_mode_vproc_chn                = "0, 0, 0, 0"
comp_mode_3dnr                     = "0"
;;;;;;;;;;;;;;mce_parameter;;;;;;;;;;;;;;
[mce_1]
;; the id of vproc chn frame pool to send to mce
mce_chn_id                         = "3"
[debug_1]
debug_deflicker_enable             = "1"
[vp2vo_1]
vp2vo_chn_id                       = "0"