/******************************************************************************
 Copyright (C), 2022 Shenzhen Oritek Semiconductors Co., Ltd. All right reserved.
******************************************************************************
Description   : the VPROC error code.
Created       : 2022/11/16
Last Modified :
******************************************************************************/
#ifndef __OT_EIS_VPROC_ERR_H__
#define __OT_EIS_VPROC_ERR_H__

#include "ot_eis_mod.h"
#include "ot_eis_errno.h" 

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif /* __cplusplus */

/* VPROC 特有的错误码 */
typedef enum {
    OT_EIS_VPROC_ERRNO_START = 0x50,
    OT_EIS_VPROC_ERRNO_INVALID_CHN_HDL,
    OT_EIS_VPROC_ERRNO_INVALID_GRP_HDL,
    OT_EIS_VPROC_ERRNO_INVALID_PIPE_HDL,
    OT_EIS_VPROC_ERRNO_HDL_RES_SET_FAIL,
    OT_EIS_VPROC_ERRNO_HDL_RES_GET_FAIL = 0x55,
    OT_EIS_VPROC_ERRNO_ASSIGN_ID_FAIL,
    OT_EIS_VPROC_ERRNO_RECYCLE_ID_FAIL,
    OT_EIS_VPROC_ERRNO_RELATION_SET_FAIL,
    OT_EIS_VPROC_ERRNO_RELATION_EXIST,
    OT_EIS_VPROC_ERRNO_INVALID_MODE = 0x5a,
    OT_EIS_VPROC_ERRNO_INVALID_INPUT,
    OT_EIS_VPROC_ERRNO_PIPE_ATTACHED, 
    OT_EIS_VPROC_ERRNO_CHN_ATTACHED,
    OT_EIS_VPROC_ERRNO_NOT_ATTACHED,
    OT_EIS_VPROC_ERRNO_INVALID_DEPTH,
    OT_EIS_VPROC_ERRNO_INVALID_CHN_ID,
    OT_EIS_VPROC_ERRNO_INVALID_GRP_ID,
    OT_EIS_VPROC_ERRNO_INVALID_PIPE_ID,
    OT_EIS_VPROC_ERRNO_INNER_ERR
} ot_eis_vproc_errno;

/* 错误码定义 */
#define OT_EIS_ERR_VPROC_ILLEGAL_PARAM	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_ILLEGAL_PARAM)
#define OT_EIS_ERR_VPROC_NO_EXIST     	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_EXIST)
#define OT_EIS_ERR_VPROC_NULL_PTR     	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NULL_PTR)    
#define OT_EIS_ERR_VPROC_NO_SUPPORT   	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_SUPPORT)   
#define OT_EIS_ERR_VPROC_NO_ACCESS    	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_ACCESS)  
#define OT_EIS_ERR_VPROC_NO_ENABLE    	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_ENABLE)   
#define OT_EIS_ERR_VPROC_NO_DISABLE   	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_DISABLE)   
#define OT_EIS_ERR_VPROC_NO_START     	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_START)  
#define OT_EIS_ERR_VPROC_NO_STOP      	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_STOP)    
#define OT_EIS_ERR_VPROC_NO_MEM       	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_MEM)     
#define OT_EIS_ERR_VPROC_BUF_EMPTY    	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_BUF_EMPTY)    
#define OT_EIS_ERR_VPROC_BUF_FULL     	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_BUF_FULL)   
#define OT_EIS_ERR_VPROC_NO_INIT      	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_INIT)    
#define OT_EIS_ERR_VPROC_TIMEOUT      	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_TIMEOUT)     
#define OT_EIS_ERR_VPROC_INVALID_ADDR 	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_INVALID_ADDR) 
#define OT_EIS_ERR_VPROC_BUSY         	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_BUSY)
#define OT_EIS_ERR_VPROC_OVER_SIZE    	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_OVER_SIZE)    
#define OT_EIS_ERR_VPROC_NO_SPACE     	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_NO_SPACE)   
#define OT_EIS_ERR_VPROC_ALREADY_INIT 	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_ALREADY_INIT)
#define OT_EIS_ERR_VPROC_ALREADY_CREATE 	OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC,	OT_EIS_ERRNO_ALREADY_CREATE) 


/* TODO：所有补充的错误码，对外暴露的需要统一整改下 */
#define OT_EIS_ERR_VPROC_INVALID_CHN_ID     OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INVALID_CHN_ID)
#define OT_EIS_ERR_VPROC_INVALID_GRP_ID     OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INVALID_GRP_ID)
#define OT_EIS_ERR_VPROC_INVALID_PIPE_ID    OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INVALID_PIPE_ID)
#define OT_EIS_ERR_VPROC_HDL_RES_GET_FAIL   OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_HDL_RES_GET_FAIL)
#define OT_EIS_ERR_VPROC_ASSIGN_ID_FAIL     OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_ASSIGN_ID_FAIL)
#define OT_EIS_ERR_VPROC_RECYCLE_ID_FAIL    OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_RECYCLE_ID_FAIL)
#define OT_EIS_ERR_VPROC_RELATION_SET_FAIL  OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_RELATION_SET_FAIL)
#define OT_EIS_ERR_VPROC_RELATION_EXIST     OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_RELATION_EXIST)
#define OT_EIS_ERR_VPROC_INVALID_MOD        OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INVALID_MODE)
#define OT_EIS_ERR_VPROC_INVALID_INPUT      OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INVALID_INPUT)
#define OT_EIS_ERR_VPROC_PIPE_ATTACHED      OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_PIPE_ATTACHED)
#define OT_EIS_ERR_VPROC_CHN_ATTACHED       OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_CHN_ATTACHED)
#define OT_EIS_ERR_VPROC_NOT_ATTACHED       OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_NOT_ATTACHED)
#define OT_EIS_ERR_VPROC_INVALID_DEPTH      OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INVALID_DEPTH)
#define OT_EIS_ERR_VPROC_INNER_ERR          OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INNER_ERR)
#define OT_EIS_ERR_VPROC_INVALID_CHN_HDL    OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INVALID_CHN_HDL)
#define OT_EIS_ERR_VPROC_INVALID_GRP_HDL    OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INVALID_GRP_HDL)
#define OT_EIS_ERR_VPROC_INVALID_PIPE_HDL   OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VPROC, OT_EIS_VPROC_ERRNO_INVALID_PIPE_HDL)


#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif