CUR_DIR=$(shell pwd)
MAIN_DIR = $(CUR_DIR)/../main
all:
	@echo "update tools libs"
	@cp $(MAIN_DIR)/out/lib/libot_isp.so $(CUR_DIR)/board/LQ560V100_PQ/libs -rf
	@cp $(MAIN_DIR)/out/lib/libot_ae.so $(CUR_DIR)/board/LQ560V100_PQ/libs -rf
	@cp $(MAIN_DIR)/out/lib/libot_awb.so $(CUR_DIR)/board/LQ560V100_PQ/libs -rf
