/*
  Copyright (c), 2001-2022, Oritek Tech. Co., Ltd.
 */

#ifndef OT_EIS_SCENE_ERRNO_H
#define OT_EIS_SCENE_ERRNO_H

#include "ot_eis_type.h"
#include "ot_eis_mod.h"
#include "ot_eis_errno.h"
#include "ot_eis_video.h"
#include "ot_eis_vi_alg.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

typedef enum {
    OT_ERRNO_EIS_SCENE_NOT_READY             = 0x70,
    OT_ERRNO_EIS_SCENE_INVALID_PIPE_HDL      = 0x71,
    OT_ERRNO_EIS_SCENE_INVALID_CHN_HDL       = 0x72,

    OT_ERRNO_EIS_SCENE_NOT_INIT              = 0x73,
    OT_ERRNO_EIS_SCENE_EINTER                = 0x74, /* Internal error */
    OT_ERRNO_EIS_SCENE_ALREADY_INIT          = 0x75,

    OT_ERRNO_EIS_SCENE_BUTT
} ot_eis_scene_err_code;


#define OT_ERR_EIS_SCENE_ILLEGAL_PARAM      OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_ILLEGAL_PARAM)
#define OT_ERR_EIS_SCENE_NULL_PTR           OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_NULL_PTR)
#define OT_ERR_EIS_SCENE_NOT_SUPPORT        OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_NO_SUPPORT)
#define OT_ERR_EIS_SCENE_NOT_ENABLE         OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_NO_ENABLE)
#define OT_ERR_EIS_SCENE_NOT_DISABLE        OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_NO_DISABLE)
#define OT_ERR_EIS_SCENE_NO_MEM             OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_NO_MEM)
#define OT_ERR_EIS_SCENE_BUF_EMPTY          OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_BUF_EMPTY)
#define OT_ERR_EIS_SCENE_BUF_FULL           OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_BUF_FULL)
#define OT_ERR_EIS_SCENE_NOT_READY          OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_ERRNO_EIS_SCENE_NOT_READY)
#define OT_ERR_EIS_SCENE_TIMEOUT            OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_TIMEOUT)
#define OT_ERR_EIS_SCENE_BUSY               OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_BUSY)
#define OT_ERR_EIS_SCENE_OVER_SIZE          OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_EIS_ERRNO_OVER_SIZE)

#define OT_ERR_EIS_SCENE_INVALID_PIPE_HDL   OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_ERRNO_EIS_SCENE_INVALID_PIPE_HDL)
#define OT_ERR_EIS_SCENE_INVALID_CHN_HDL    OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_ERRNO_EIS_SCENE_INVALID_CHN_HDL)

#define OT_ERR_EIS_SCENE_EINTER             OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_ERRNO_EIS_SCENE_EINTER)
#define OT_ERR_EIS_SCENE_NOT_INIT           OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_ERRNO_EIS_SCENE_NOT_INIT)
#define OT_ERR_EIS_SCENE_ALREADY_INIT       OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_SCENE_AUTO, OT_ERRNO_EIS_SCENE_ALREADY_INIT)

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* End of #ifndef OT_EIS_SCENE_ERRNO_H */
