#ifndef OT_EIS_VI_SERDES_ERRNO_H
#define OT_EIS_VI_SERDES_ERRNO_H

#include "ot_eis_errno.h"
#include "ot_eis_mod.h"

#ifdef __cplusplus
extern "C"{
#endif /* __cplusplus */

// common errno
#define OT_VI_SERDES_ERR_NOT_INIT           OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_NO_INIT)
#define OT_VI_SERDES_ERR_INVALID_PARAM      OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_ILLEGAL_PARAM)
#define OT_VI_SERDES_ERR_NO_START           OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_NO_START)
#define OT_VI_SERDES_ERR_NO_STOP            OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_NO_STOP)
#define OT_VI_SERDES_ERR_NO_MEM             OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_NO_MEM)
#define OT_VI_SERDES_ERR_NULL_PTR           OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_NULL_PTR)
#define OT_VI_SERDES_ERR_ALREADY_CREATE     OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_ALREADY_CREATE)
#define OT_VI_SERDES_ERR_OVER_SIZE          OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_OVER_SIZE)
#define OT_VI_SERDES_ERR_OP_FAILED          OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_NO_SUPPORT)
#define OT_VI_SERDES_ERR_NO_EXIST           OT_EIS_ERRNO_DEFINE(OT_EIS_MODULE_VI_SERDES, OT_EIS_ERRNO_NO_EXIST)

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* OT_EIS_VI_SERDES_ERRNO_H */
