#!/bin/sh
# Usage: ./load_lq560v100_quickboot_stage_x [ -r|-i|-a ] [ -sensor0~3 ]
#         -r : rmmod all modules
#         -i : insmod all modules
#         -a : rmmod all moules and then insmod them
# e.g: ./load_lq560v100_quickboot_stage_x -a

GYRO_EN=0    # 0 - not load gyro's ko, 1 - load gyro's ko

function insert_gyro()
{
    insmod ot_sys_adapter.ko
    insmod ot_spi.ko spi=3
    insmod ot_gyrodis.ko
    insmod ot_motionfusion.ko
    insmod motionsensor_mng.ko
    insmod motionsensor_chip.ko
}

function remove_gyro()
{
    rmmod motionsensor_chip
    rmmod motionsensor_mng
    rmmod ot_motionfusion
    rmmod ot_gyrodis
    rmmod ot_spi
    rmmod ot_sys_adapter.ko
}

function insert_ko()
{
    insmod ot_oge.ko
    insmod ot_gfb.ko video="gfb:vram0_size:16200"
    insmod ot_vfmw.ko
    insmod ot_venc.ko
    insmod ot_venc_svr.ko
    insmod ot_h264e.ko
    insmod ot_h265e.ko
    insmod ot_jpege.ko
    insmod ot_jpegd.ko
    insmod ot_vdec.ko
    insmod ot_cve.ko save_power=1
    insmod ot_avp_npu.ko
    insmod ot_aio.ko
    insmod ot_ao.ko
    insmod ot_acodec.ko
    # insmod ot_tlv320aic3101.ko
    insmod ot_cipher.ko
    insmod ot_km.ko
    insmod ot_adc.ko
    insmod ot_wdg.ko
    insmod ot_proc.ko
    insmod ot_avp_dpu_rect.ko
    insmod ot_avp_dpu_match.ko
if [ "$GYRO_EN" = "1" ]; then
    insert_gyro
fi
}

function remove_ko()
{
if [ "$GYRO_EN" = "1" ]; then
    remove_gyro
fi
    rmmod ot_dpu_match
    rmmod ot_dpu_rect
    rmmod ot_proc
    rmmod ot_wdg
    rmmod ot_adc
    rmmod ot_km
    rmmod ot_cipher
    # rmmod ot_tlv320aic3101
    rmmod ot_acodec
    rmmod ot_ao
    rmmod ot_aio
    rmmod ot_avp_npu
    rmmod ot_cve
    rmmod ot_vdec
    rmmod ot_jpegd
    rmmod ot_jpege
    rmmod ot_h265e
    rmmod ot_h264e
    rmmod ot_venc_svr
    rmmod ot_venc
    rmmod ot_vfmw
    rmmod ot_gfb
    rmmod ot_oge
}

load_usage()
{
    echo "Usage:  $0 [-option] [-sensor0~3] "
    echo "options:"
    echo "    -i                       insert modules"
    echo "    -r                       remove modules"
    echo "    -a                       remove modules first, then insert modules"
    echo "    -h                       help information"
    echo -e "Available sensors:os04a10 "
    echo -e "for example: $0 -i\n"
}

b_arg_insmod=0
b_arg_remove=0
function parse_arg()
{
    ######################parse arg###################################
    for arg in $@
    do
        case $arg in
            "-i")
                b_arg_insmod=1;
                ;;
            "-r")
                b_arg_remove=1;
                ;;
            "-a")
                b_arg_insmod=1;
                b_arg_remove=1;
                ;;
            "-h")
                load_usage;
                ;;
       esac
    done
    #######################parse arg end########################
}

if [ $# -lt 1 ]; then
    load_usage;
    exit 0;
fi

parse_arg $@

#######################Action###############################
if [ $b_arg_remove -eq 1 ]; then
    remove_ko;
fi

if [ $b_arg_insmod -eq 1 ]; then
    insert_ko;
fi
