#!/bin/sh
# Usage: ./load_lq560v100 [ -r|-i|-a ] [ -sensor0~3 ]
#         -r : rmmod all modules
#         -i : insmod all modules
#         -a : rmmod all moules and then insmod them
# -sensor0-3 : sensor0~sensor3 config, default: os04a10
#     -board : board config, default: dmeb
#   -vo_intf : vo intf of bt1120/mipitx/none, default: bt1120
# e.g: ./load_lq560v100 -a -sensor0 os04a10 -vo_intf bt1120 -board dmeb

####### select sensor type for your test ########################
####      os04a10              ####
####################Variables Definition##########################

SNS_TYPE0=os04a10;               # sensor type
SNS_TYPE1=os04a10;               # sensor type
SNS_TYPE2=os04a10;               # sensor type
SNS_TYPE3=os04a10;               # sensor type
BOARD=dmeb;                      # sck dmeb dmebpro

VO_INTF=mipitx                   # mipitx bt1120 bt656 rgb6bit rgb8bit rgb16bit rgb18bit rgb24bit
MIPITX_SWI=0                     # 0 - mipitx to lvds via serdes, 1 - mipitx direct or mipitx to lvds via conversion chip
QUICKBOOT_EN=0                   # 0 - quickboot disable, 1 - quickboot enable
GYRO_EN=1                        # 0 - not load gyro's ko, 1 - load gyro's ko

# DDR start:    0x40000000
# 192K, FDT&ATF mem
# kernel start: 0x40030000
# 132928K(1856K+128M), os mem
# SMR start:    0x48200000
# 894M, smr mem

smr_start=0x48200000;         # smr start addr, default:0x48200000 (0x40000000+0x30000(FDT&ATF)+0x81D0000(OS))
smr_size=894M;               # smr size, default:894M (1024M-130M)
##################################################################

function report_error()
{
    echo "******* Error: There's something wrong, please check! *****"
    exit 1
}

function insert_gyro()
{
    insmod ot_sys_adapter.ko
    insmod ot_spi.ko spi=3
    insmod ot_gyrodis.ko
    insmod ot_motionfusion.ko
    insmod motionsensor_mng.ko
    insmod motionsensor_chip.ko
}

function remove_gyro()
{
    rmmod motionsensor_chip
    rmmod motionsensor_mng
    rmmod ot_motionfusion
    rmmod ot_gyrodis
    rmmod ot_spi
    rmmod ot_sys_adapter.ko
}

function insert_ko()
{
    insmod sys_config.ko sensors=sns0=$SNS_TYPE0,sns1=$SNS_TYPE1,sns2=$SNS_TYPE2,sns3=$SNS_TYPE3 board=$BOARD vo_intf=$VO_INTF mipitx_swi=$MIPITX_SWI quickboot_en=$QUICKBOOT_EN ir_auto=$IR_AUTO || exit 1
    insmod ot_osal.ko
    insmod ot_smr.ko anony=1 smr_allocator=ot smr=anonymous,0,$smr_start,$smr_size$1 mem_process_isolation=0 || report_error
    insmod ot_base.ko
    insmod ot_vrb.ko
    insmod ot_vca.ko
    insmod ot_sys.ko
    insmod ot_oge.ko
    insmod ot_rgn.ko
    insmod ot_gdc.ko
    insmod ot_vpp.ko
    insmod ot_vgs.ko
    insmod ot_dis.ko
    insmod ot_vi.ko
    insmod ot_isp.ko
    insmod ot_vproc.ko
    insmod ot_vo_dev.ko
    insmod ot_vo.ko
    insmod ot_gfb.ko video="gfb:vram0_size:16200"
    insmod ot_chnl.ko
    insmod ot_vfmw.ko
    insmod ot_rc.ko
    insmod ot_venc.ko
    insmod ot_venc_svr.ko
    insmod ot_h264e.ko
    insmod ot_h265e.ko
    insmod ot_jpege.ko
    insmod ot_jpegd.ko
    insmod ot_vdec.ko
    insmod ot_cve.ko save_power=1
    insmod ot_avp_npu.ko
    insmod ot_sensor_i2c.ko
    insmod ot_mipi_tx.ko g_smooth=0
    insmod ot_aio.ko
    insmod ot_ao.ko
    insmod ot_acodec.ko
    # insmod ot_tlv320aic3101.ko
    insmod ot_mipi_rx.ko
    insmod ot_pm.ko
    insmod ot_cipher.ko
    insmod ot_km.ko
    insmod ot_otp.ko
    insmod ot_vo_res_mng.ko
    insmod ot_vproc_res_mng.ko
    insmod ot_adc.ko
    insmod ot_vi_res_mng.ko
    insmod ot_wdg.ko
    insmod ot_proc.ko
    insmod ot_avp_dpu_rect.ko
    insmod ot_avp_dpu_match.ko
if [ "$GYRO_EN" = "1" ]; then
    insert_gyro
fi
}

function remove_ko()
{
if [ "$GYRO_EN" = "1" ]; then
    remove_gyro
fi
    rmmod ot_dpu_match
    rmmod ot_dpu_rect
    rmmod ot_proc
    rmmod ot_wdg
    rmmod ot_vi_res_mng
    rmmod ot_adc
    rmmod ot_vproc_res_mng
    rmmod ot_vo_res_mng
    rmmod ot_otp
    rmmod ot_km
    rmmod ot_cipher
    rmmod ot_pm
    rmmod ot_mipi_rx
    # rmmod ot_tlv320aic3101
    rmmod ot_acodec
    rmmod ot_ao
    rmmod ot_aio
    rmmod ot_mipi_tx
    rmmod ot_sensor_i2c
    rmmod ot_avp_npu
    rmmod ot_cve
    rmmod ot_vdec
    rmmod ot_jpegd
    rmmod ot_jpege
    rmmod ot_h265e
    rmmod ot_h264e
    rmmod ot_venc_svr
    rmmod ot_venc
    rmmod ot_rc
    rmmod ot_vfmw
    rmmod ot_chnl
    rmmod ot_gfb
    rmmod ot_vo
    rmmod ot_vo_dev
    rmmod ot_vproc
    rmmod ot_isp
    rmmod ot_vi
    rmmod ot_dis
    rmmod ot_vgs
    rmmod ot_vpp
    rmmod ot_gdc
    rmmod ot_rgn
    rmmod ot_oge
    rmmod ot_sys
    rmmod ot_vca
    rmmod ot_vrb
    rmmod ot_base
    rmmod ot_smr
    rmmod ot_osal
    rmmod sys_config
}

load_usage()
{
    echo "Usage:  $0 [-option] [-sensor0~3] "
    echo "options:"
    echo "    -i                       insert modules"
    echo "    -r                       remove modules"
    echo "    -a                       remove modules first, then insert modules"
    echo "    -vo_intf vo intf type    config vo intf          [default: bt1120]"
    echo "    -mipitx_swi value        config mipitx swi       [default: 0]"
    echo "    -quickboot_en enable     config quickboot enable [default: 0]"
    echo "    -sensor0~3 sensor_name   config sensor type      [default: os04a10]"
    echo "    -board board_name        config board type       [default: dmeb]"
    echo "    -smr_start               config SMR start addr   [default: 0x48200000]"
    echo "    -smr_size                config SMR mem size     [unit: M, default: 1918M]"
    echo "    -ir_auto                 config ir_auto enable   [default: 1]"
    echo "    -h                       help information"
    echo -e "Available sensors:os04a10 "
    echo -e "for example: $0 -i -vo_intf bt1120 -mipitx_swi 0 -quickboot_en 0 -sensor0 os04a10 -sensor1 os04a10 -sensor2 os04a10 -sensor3 os04a10 -board dmeb -smr_start 0x48200000 -smr_size 1918M -ir_auto 1\n"
}

b_arg_insmod=0
b_arg_remove=0
function parse_arg()
{
    ######################parse arg###################################
    b_arg_sensor0=0
    b_arg_sensor1=0
    b_arg_sensor2=0
    b_arg_sensor3=0
    b_arg_smr_start=0
    b_arg_smr_size=0
    b_arg_vo_intf=0
    b_arg_mipitx_swi=0
    b_arg_quickboot_en=0
    b_arg_board=0

    for arg in $@
    do
        if [ $b_arg_sensor0 -eq 1 ] ; then
            b_arg_sensor0=0;
            SNS_TYPE0=$arg;
        fi
        if [ $b_arg_sensor1 -eq 1 ] ; then
            b_arg_sensor1=0;
            SNS_TYPE1=$arg;
        fi
        if [ $b_arg_sensor2 -eq 1 ] ; then
            b_arg_sensor2=0;
            SNS_TYPE2=$arg;
        fi
        if [ $b_arg_sensor3 -eq 1 ] ; then
            b_arg_sensor3=0;
            SNS_TYPE3=$arg;
        fi

        if [ $b_arg_board -eq 1 ] ; then
            b_arg_board=0;
            BOARD=$arg;
        fi

        if [ $b_arg_vo_intf -eq 1 ] ; then
            b_arg_vo_intf=0;
            VO_INTF=$arg;
        fi

        if [ $b_arg_mipitx_swi -eq 1 ] ; then
            b_arg_mipitx_swi=0;
            MIPITX_SWI=$arg;
        fi

        if [ $b_arg_quickboot_en -eq 1 ] ; then
            b_arg_quickboot_en=0;
            QUICKBOOT_EN=$arg;
        fi

        if [ $b_arg_smr_start -eq 1 ] ; then
            b_arg_smr_start=0;
            smr_start=$arg;

            if [ -z $smr_start ]; then
                echo "[error] smr_start is null"
                exit;
            fi
        fi

        if [ $b_arg_smr_size -eq 1 ] ; then
            b_arg_smr_size=0;
            smr_size=$arg;

            if [ -z $smr_size ]; then
                echo "[error] smr_size is null"
                exit;
            fi
        fi

        case $arg in
            "-i")
                b_arg_insmod=1;
                ;;
            "-r")
                b_arg_remove=1;
                ;;
            "-a")
                b_arg_insmod=1;
                b_arg_remove=1;
                ;;
            "-h")
                load_usage;
                ;;
            "-sensor0")
                b_arg_sensor0=1;
                ;;
            "-sensor")
                b_arg_sensor0=1;
                ;;
            "-sensor1")
                b_arg_sensor1=1;
                ;;
            "-sensor2")
                b_arg_sensor2=1;
                ;;
            "-sensor3")
                b_arg_sensor3=1;
                ;;
            "-board")
                b_arg_board=1;
                ;;
            "-vo_intf")
                b_arg_vo_intf=1;
                ;;
            "-mipitx_swi")
                b_arg_mipitx_swi=1;
                ;;
            "-quickboot_en")
                b_arg_quickboot_en=1;
                ;;
            "-smr_size")
                b_arg_smr_size=1;
                ;;
            "-smr_start")
                b_arg_smr_start=1;
                ;;
        esac
    done
    #######################parse arg end########################
}

if [ $# -lt 1 ]; then
    load_usage;
    exit 0;
fi

parse_arg $@

#######################Action###############################
if [ $b_arg_remove -eq 1 ]; then
    remove_ko;
fi

if [ $b_arg_insmod -eq 1 ]; then
    insert_ko;
fi
